USE [master]
GO

/****** Object:  Database [DoctorDb]    Script Date: 27-04-2020 10:55:00 ******/
CREATE DATABASE [DoctorDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DoctorDb', FILENAME = N'[provide local path]' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DoctorDb_log', FILENAME = N'[provide local path]' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DoctorDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DoctorDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DoctorDb] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [DoctorDb] SET ANSI_NULLS ON 
GO

ALTER DATABASE [DoctorDb] SET ANSI_PADDING ON 
GO

ALTER DATABASE [DoctorDb] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [DoctorDb] SET ARITHABORT ON 
GO

ALTER DATABASE [DoctorDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DoctorDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DoctorDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DoctorDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DoctorDb] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [DoctorDb] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [DoctorDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DoctorDb] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [DoctorDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DoctorDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DoctorDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DoctorDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DoctorDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DoctorDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DoctorDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DoctorDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DoctorDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DoctorDb] SET RECOVERY FULL 
GO

ALTER DATABASE [DoctorDb] SET  MULTI_USER 
GO

ALTER DATABASE [DoctorDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DoctorDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DoctorDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DoctorDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DoctorDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DoctorDb] SET QUERY_STORE = OFF
GO

USE [DoctorDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DoctorDb] SET  READ_WRITE 
GO

USE [DoctorDb]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Doctors](
	[Id] [int] NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
