USE [master]
GO

/****** Object:  Database [PatientDb]    Script Date: 27-04-2020 10:58:21 ******/
CREATE DATABASE [PatientDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatientDb', FILENAME = N'[provide local path]' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PatientDb_log', FILENAME = N'[provide local path]' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PatientDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PatientDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PatientDb] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [PatientDb] SET ANSI_NULLS ON 
GO

ALTER DATABASE [PatientDb] SET ANSI_PADDING ON 
GO

ALTER DATABASE [PatientDb] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [PatientDb] SET ARITHABORT ON 
GO

ALTER DATABASE [PatientDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PatientDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PatientDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PatientDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PatientDb] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [PatientDb] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [PatientDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PatientDb] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [PatientDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PatientDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PatientDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PatientDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PatientDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PatientDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PatientDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PatientDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PatientDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PatientDb] SET RECOVERY FULL 
GO

ALTER DATABASE [PatientDb] SET  MULTI_USER 
GO

ALTER DATABASE [PatientDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PatientDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PatientDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PatientDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PatientDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PatientDb] SET QUERY_STORE = OFF
GO

USE [PatientDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [PatientDb] SET  READ_WRITE 
GO


USE [PatientDb]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Patients](
	[Id] [int] NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


