name: Doctor service CI CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101    
    - name: Build
      run: dotnet build 'src/Tests/Doctor/MedicalSystem.Tests.Services.Doctor.csproj' --configuration Release
    - name: Test
      run: dotnet test 'src/Tests/Doctor/MedicalSystem.Tests.Services.Doctor.csproj' --no-restore --configuration Release
  github-docker-package-deploy:
    #if: ${{ github.event_name == 'push' }}
    name: GitHub docker package deploy
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101    
    - name: Publish
      run: dotnet publish 'src/Services/Doctor/Api/MedicalSystem.Services.Doctor.Api.csproj' --configuration Release -o 'publish/app'
    - name: Docker build
      run: docker build -f 'src/Services/Doctor/Api/Dockerfile' -t docker.pkg.github.com/arnab-developer/medical-system/doctorservice:1.0.0 .
    - name: Docker push
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u Arnab-Developer --password-stdin
        docker push docker.pkg.github.com/arnab-developer/medical-system/doctorservice:1.0.0
